FROM openjdk:8-jre-alpine

ENV VERTICLE_FILE {{artifactId}}-{{artifactVersion}}-fat.jar
ENV VERTICLE_CONFIG_FILE config.json

# Set the location of the verticles
ENV VERTICLE_HOME /usr/verticles

EXPOSE 8080

# Copy your fat jar to the container
COPY target/$VERTICLE_FILE $VERTICLE_HOME/
COPY VERTICLE_CONFIG_FILE $VERTICLE_HOME/

# Launch the verticle
WORKDIR $VERTICLE_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $VERTICLE_FILE -conf $VERTICLE_CONFIG_FILE"]